# backend/generator/modules/project_scaffold.py
from pathlib import Path
from ..base import GenContext, FileOps, GenModule


class ProjectScaffoldModule(GenModule):
  """
  Creates the base project structure:
  - index.html
  - app.js
  - style.css
  - config.json
  """

  def run(self, ctx: GenContext) -> None:
    root = ctx.project_path
    FileOps.ensure_dir(root, ctx)

    index_html = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <title>{ctx.project_name}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <div id="app">
    <h1>{ctx.project_name}</h1>
    <p>Generated by Boardwalk Playground.</p>
    <div id="root"></div>
  </div>
  <script src="app.js"></script>
</body>
</html>
"""
    FileOps.write_file(root / "index.html", index_html, ctx)

    app_js = """console.log('App booted.');"""
    FileOps.write_file(root / "app.js", app_js, ctx)

    style_css = """body { font-family: system-ui, sans-serif; background:#050608; color:#f5f5f5; }"""
    FileOps.write_file(root / "style.css", style_css, ctx)

    config_json = f"""{{
  "name": "{ctx.project_name}",
  "type": "{ctx.app_type}",
  "prompt": {ctx.prompt!r}
}}
"""
    FileOps.write_file(root / "config.json", config_json, ctx)

    ctx.log("Project scaffold created.")
