# backend/generator/python_generator.py
import os
from pathlib import Path
from textwrap import dedent
from datetime import datetime

def _write_file(base_dir: Path, rel_path: str, content: str) -> None:
    target = base_dir / rel_path
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")

def generate_python_app(root_dir: str, project_name: str, spec: dict | None = None) -> dict:
    """
    Generate a basic Python app project.
    """
    spec = spec or {}
    base = Path(root_dir) / project_name

    _write_file(base, "main.py", dedent(f"""
    import sys

    def main():
        print("Hello from {project_name}!")

    if __name__ == "__main__":
        main()
    """).strip() + "\n")

    _write_file(base, "requirements.txt", "# Add your Python dependencies here\n")

    _write_file(base, "README.md", dedent(f"""
    # {project_name}

    Generated by Boardwalk Playground Python Engine.

    ## Run

    python3 main.py
    """).strip() + "\n")

    _write_file(base, ".playground.json", dedent(f"""
    {{
      "type": "python-app",
      "name": "{project_name}",
      "createdAt": "{datetime.utcnow().isoformat()}Z",
      "spec": {spec!r}
    }}
    """).strip() + "\n")

    return {
        "ok": True,
        "project_root": str(base),
        "type": "python-app",
    }

def generate_python_backend(root_dir: str, project_name: str, spec: dict | None = None) -> dict:
    """
    Generate a simple FastAPI backend.
    """
    spec = spec or {}
    base = Path(root_dir) / project_name

    _write_file(base, "app.py", dedent("""
    from fastapi import FastAPI

    app = FastAPI()

    @app.get("/")
    def read_root():
        return {"message": "Hello from FastAPI backend"}
    """).strip() + "\n")

    _write_file(base, "requirements.txt", "fastapi\nuvicorn\n")

    _write_file(base, "run.sh", "#!/usr/bin/env bash\nuvicorn app:app --reload --host 0.0.0.0 --port 8000\n")

    os.chmod(base / "run.sh", 0o755)

    _write_file(base, "README.md", dedent(f"""
    # {project_name} (Python Backend)

    ## Run

    ./run.sh
    """).strip() + "\n")

    _write_file(base, ".playground.json", dedent(f"""
    {{
      "type": "python-backend",
      "name": "{project_name}",
      "createdAt": "{datetime.utcnow().isoformat()}Z",
      "spec": {spec!r}
    }}
    """).strip() + "\n")

    return {
        "ok": True,
        "project_root": str(base),
        "type": "python-backend",
    }
