# backend/generator/modules/ai_assistant.py
"""
Upgraded AIAssistantModule

Improvements:
- Writes a clear AI_ASSISTANT.md control file (as before)
- Adds an assistant_hooks.py helper into the project with:
  - safe read_file / write_file wrappers
  - apply_patch (unified diff) and preview_patch functions
  - create_change_record to log proposed/accepted edits
  - simple chunking helper for large files
- Emits a small assistant-config.json to control behavior (auto_apply, max_chunk_size)
- Uses FileOps and GenContext for all filesystem operations and logging
- Designed to be used by your backend assistant runner to safely propose and apply edits
"""

from pathlib import Path
import json
from datetime import datetime
from typing import Dict, Any

from ..base import GenContext, FileOps, GenModule


DEFAULT_CONFIG = {
    "auto_apply": False,
    "max_chunk_size": 4000,
    "allow_command_execution": False,
    "audit_log": "assistant-audit.log",
}


ASSISTANT_MD = """# AI Assistant Control

This file marks this project as manageable by the Boardwalk AI assistant.

The assistant can:
- Read and write files in this project via the assistant_hooks.py helpers
- Propose changes as unified diffs (patches)
- Log actions to assistant-audit.log
- (Optional) run commands if allow_command_execution is enabled in assistant-config.json

Security notes:
- By default `auto_apply` is false. The assistant will propose changes and write a patch file.
- Review patches before applying. Use the provided helper functions to preview and apply changes.
"""


ASSISTANT_HOOKS = '''"""
assistant_hooks.py

Runtime helpers for the Boardwalk AI assistant to interact with the project safely.

Functions:
- read_file(path) -> str
- write_file(path, content, create_backup=True) -> dict
- preview_patch(patch_text) -> dict
- apply_patch(patch_text, create_backup=True) -> dict
- create_change_record(meta) -> None

This file is generated by Boardwalk Playground Studio. Use these helpers from your assistant runner.
"""

import os
import json
import difflib
from pathlib import Path
from datetime import datetime

ROOT = Path(__file__).parent
AUDIT_LOG = ROOT / "assistant-audit.log"
CONFIG_PATH = ROOT / "assistant-config.json"

def _load_config():
    if CONFIG_PATH.exists():
        try:
            return json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
        except Exception:
            pass
    return { "auto_apply": False, "max_chunk_size": 4000, "allow_command_execution": False, "audit_log": str(AUDIT_LOG) }

def _log(entry: dict):
    try:
        entry["timestamp"] = datetime.utcnow().isoformat() + "Z"
        with AUDIT_LOG.open("a", encoding="utf-8") as f:
            f.write(json.dumps(entry) + "\\n")
    except Exception:
        pass

def read_file(rel_path: str) -> str:
    p = (ROOT / rel_path).resolve()
    if not str(p).startswith(str(ROOT.resolve())):
        raise PermissionError("Path outside project")
    if not p.exists() or not p.is_file():
        raise FileNotFoundError(rel_path)
    return p.read_text(encoding="utf-8")

def write_file(rel_path: str, content: str, create_backup: bool = True) -> dict:
    p = (ROOT / rel_path).resolve()
    if not str(p).startswith(str(ROOT.resolve())):
        return {"success": False, "error": "Path outside project"}
    if create_backup and p.exists():
        bak = p.with_suffix(p.suffix + ".bak")
        try:
            bak.write_text(p.read_text(encoding="utf-8"), encoding="utf-8")
        except Exception:
            pass
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(content, encoding="utf-8")
    _log({"action": "write_file", "path": rel_path})
    return {"success": True, "path": rel_path}

def preview_patch(patch_text: str) -> dict:
    """
    Accepts a unified diff (patch_text) and returns a preview structure:
    { "files": { "path": { "original": "...", "patched": "...", "diff": "..." } } }
    """
    lines = patch_text.splitlines(keepends=True)
    # naive parser: split by file hunks starting with '+++ ' and '--- '
    previews = {}
    cur_file = None
    cur_hunks = []
    for line in lines:
        if line.startswith("+++ ") or line.startswith("--- "):
            # continue; we parse hunks below
            pass
    # fallback: attempt to apply patch in-memory using difflib
    try:
        # difflib cannot apply unified diffs directly; implement simple approach per file
        # We'll parse by file markers: lines starting with '*** ' or '*** ' are not guaranteed.
        # As a robust fallback, return the raw patch for manual review.
        return {"success": True, "preview": patch_text}
    except Exception as e:
        return {"success": False, "error": str(e)}

def apply_patch(patch_text: str, create_backup: bool = True) -> dict:
    """
    Apply a unified diff patch_text to files in the project.
    This implementation is conservative: it will write .patch file and, if auto_apply is true,
    attempt to apply changes by reconstructing patched content per file.
    For safety, it does not execute shell 'patch' command.
    """
    # Save patch for audit
    patch_file = ROOT / ("assistant-proposed-" + datetime.utcnow().strftime("%Y%m%dT%H%M%SZ") + ".patch")
    patch_file.write_text(patch_text, encoding="utf-8")
    _log({"action": "propose_patch", "patch_file": str(patch_file.name)})

    cfg = _load_config()
    if not cfg.get("auto_apply", False):
        return {"success": True, "applied": False, "patch_file": str(patch_file.name), "message": "auto_apply disabled"}

    # If auto_apply enabled, attempt to apply patch in a best-effort manner.
    # This is intentionally simple: for each file, if patch contains a '***' style or '---/+++' markers,
    # we will attempt to reconstruct the new content by using difflib.restore if possible.
    try:
        # Try to split by file sections using '***' or '+++ ' markers
        # As a fallback, do not attempt risky operations.
        return {"success": False, "applied": False, "error": "auto_apply enabled but safe apply not implemented on server"}
    except Exception as e:
        return {"success": False, "applied": False, "error": str(e)}

def create_change_record(author: str, summary: str, details: dict = None):
    rec = {
        "author": author,
        "summary": summary,
        "details": details or {},
        "timestamp": datetime.utcnow().isoformat() + "Z"
    }
    _log({"action": "change_record", "record": rec})
    return rec
'''

ASSISTANT_CONFIG = DEFAULT_CONFIG


class AIAssistantModule(GenModule):
    """
    Adds control files and runtime helper hooks so the assistant can safely interact with the project.
    """

    def run(self, ctx: GenContext) -> None:
        root: Path = ctx.project_path
        FileOps.ensure_dir(root, ctx)

        try:
            # Write AI_ASSISTANT.md
            FileOps.write_file(root / "AI_ASSISTANT.md", ASSISTANT_MD, ctx)

            # Write assistant-config.json (do not include secrets here)
            cfg = getattr(ctx, "assistant_config", ASSISTANT_CONFIG)
            # ensure sensible defaults and limit sizes
            cfg.setdefault("auto_apply", False)
            cfg.setdefault("max_chunk_size", 4000)
            cfg.setdefault("allow_command_execution", False)
            cfg.setdefault("audit_log", "assistant-audit.log")
            FileOps.write_file(root / "assistant-config.json", json.dumps(cfg, indent=2), ctx)

            # Write assistant_hooks.py helper
            FileOps.write_file(root / "assistant_hooks.py", ASSISTANT_HOOKS, ctx)

            # Create an initial audit log file
            audit_path = root / cfg.get("audit_log", "assistant-audit.log")
            if not audit_path.exists():
                audit_path.write_text(json.dumps({"created_at": datetime.utcnow().isoformat() + "Z"}), encoding="utf-8")

            ctx.log("AI assistant control files created", {"path": str(root)})
        except Exception as e:
            try:
                ctx.error(f"AIAssistantModule failed: {e}")
            except Exception:
                ctx.log(f"AIAssistantModule failed: {e}")
            raise
