# backend/generator/modules/auth_security.py
"""
Upgraded AuthSecurityModule

Improvements:
- Uses a secure PBKDF2-HMAC hashing scheme with random salt
- Writes structured auth-config.json with algorithm, iterations, salt, and derived_key
- Emits a small auth_helpers.py into the project to help runtime verification
- Provides functions to rotate the secret and to verify a provided secret
- Uses FileOps and GenContext logging
"""

from pathlib import Path
import json
import os
import hashlib
import base64
import secrets
from typing import Dict, Any

from ..base import GenContext, FileOps, GenModule

# Configurable defaults
_DEFAULT_ALGORITHM = "sha256"
_DEFAULT_ITERATIONS = 120_000
_DERIVED_KEY_BYTES = 32


def _derive_key(secret: str, salt: bytes, iterations: int = _DEFAULT_ITERATIONS, algo: str = _DEFAULT_ALGORITHM) -> bytes:
    """
    Derive a key from a secret using PBKDF2-HMAC.
    """
    return hashlib.pbkdf2_hmac(algo, secret.encode("utf-8"), salt, iterations, dklen=_DERIVED_KEY_BYTES)


def _b64(b: bytes) -> str:
    return base64.b64encode(b).decode("ascii")


def _unb64(s: str) -> bytes:
    return base64.b64decode(s.encode("ascii"))


class AuthSecurityModule(GenModule):
    """
    Adds basic auth/security config and helper files to the generated project.

    Writes:
    - auth-config.json  (structured config with salt, iterations, algorithm, derived_key)
    - auth_helpers.py   (small runtime helper to verify secrets)
    """

    def run(self, ctx: GenContext) -> None:
        root: Path = ctx.project_path
        FileOps.ensure_dir(root, ctx)

        try:
            # Create a random salt and derive a key from a seed based on project name + prompt
            seed_input = f"{getattr(ctx, 'project_name', '')}:{getattr(ctx, 'prompt', '')}"
            # If GenContext provides a hash_string helper, use it to mix into the seed (non-essential)
            try:
                seed_mixin = getattr(ctx, "hash_string", None)
                if callable(seed_mixin):
                    seed_input = seed_mixin(seed_input)
            except Exception:
                pass

            # Generate salt and derive key
            salt = secrets.token_bytes(16)
            iterations = _DEFAULT_ITERATIONS
            algo = _DEFAULT_ALGORITHM
            derived = _derive_key(seed_input, salt, iterations=iterations, algo=algo)

            config: Dict[str, Any] = {
                "auth_enabled": False,
                "algorithm": algo,
                "iterations": iterations,
                "salt": _b64(salt),
                "derived_key": _b64(derived),
                "note": "auth_enabled=false by default. Use auth_helpers.py to verify or rotate secrets.",
            }

            # Write auth-config.json
            FileOps.write_file(root / "auth-config.json", json.dumps(config, indent=2), ctx)

            # Write a small runtime helper module to verify secrets and rotate keys
            helper_code = f'''"""
auth_helpers.py

Runtime helpers for verifying and rotating the project secret.
This file is generated by Boardwalk Playground Studio.
"""

import json
import hashlib
import base64
from pathlib import Path
from typing import Dict

_CONFIG_PATH = Path(__file__).parent / "auth-config.json"

def _b64(s: bytes) -> str:
    return base64.b64encode(s).decode("ascii")

def _unb64(s: str) -> bytes:
    return base64.b64decode(s.encode("ascii"))

def _derive_key(secret: str, salt: bytes, iterations: int, algo: str, dklen: int = { _DERIVED_KEY_BYTES }) -> bytes:
    return hashlib.pbkdf2_hmac(algo, secret.encode("utf-8"), salt, iterations, dklen=dklen)

def load_config() -> Dict:
    with _CONFIG_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)

def verify_secret(candidate: str) -> bool:
    """
    Verify a candidate secret against the stored derived_key.
    Returns True if it matches, False otherwise.
    """
    cfg = load_config()
    if not cfg.get("auth_enabled", False):
        # If auth is disabled, treat verification as successful
        return True
    algo = cfg.get("algorithm", "{algo}")
    iterations = int(cfg.get("iterations", {iterations}))
    salt = _unb64(cfg["salt"])
    expected = _unb64(cfg["derived_key"])
    derived = _derive_key(candidate, salt, iterations, algo, dklen=len(expected))
    return derived == expected

def rotate_secret(new_secret: str, enable_auth: bool = True) -> Dict:
    """
    Replace the stored derived key with one derived from new_secret.
    Returns the new config dict.
    """
    cfg = load_config()
    salt = secrets.token_bytes(16)
    algo = cfg.get("algorithm", "{algo}")
    iterations = int(cfg.get("iterations", {iterations}))
    derived = _derive_key(new_secret, salt, iterations, algo, dklen={ _DERIVED_KEY_BYTES })
    cfg["salt"] = _b64(salt)
    cfg["derived_key"] = _b64(derived)
    cfg["auth_enabled"] = bool(enable_auth)
    with _CONFIG_PATH.open("w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2)
    return cfg

if __name__ == "__main__":
    print("This module provides verify_secret(candidate) and rotate_secret(new_secret).")
'''

            FileOps.write_file(root / "auth_helpers.py", helper_code, ctx)

            ctx.log("Auth/security config created", {"path": str(root / "auth-config.json")})
        except Exception as e:
            try:
                ctx.error(f"AuthSecurityModule failed: {e}")
            except Exception:
                ctx.log(f"AuthSecurityModule failed: {e}")
            raise
