# backend/generator/modules/backend_service.py
"""
Upgraded BackendServiceModule

Improvements:
- Writes a structured backend-services.json describing routes and service metadata
- Emits a minimal FastAPI service scaffold (server.py) that maps routes described in the descriptor
- Adds a Dockerfile and Procfile for easy local/container deployment
- Adds a small healthcheck endpoint and example route wiring
- Uses FileOps and GenContext for safe writes and logging
- Keeps generated code minimal and dependency-light (FastAPI/uvicorn recommended)
"""

from pathlib import Path
import json
from datetime import datetime
from typing import Dict, Any

from ..base import GenContext, FileOps, GenModule


DEFAULT_DESCRIPTOR = {
    "services": [
        {
            "name": "default",
            "description": "Primary backend service for the generated app",
            "language": "python",
            "framework": "fastapi",
            "routes": [
                {"path": "/", "method": "GET", "description": "Root health/info"},
                {"path": "/api/hello", "method": "GET", "description": "Example API route returning hello"},
            ],
            "env": {"PORT": 8000},
        }
    ],
    "generated_at": datetime.utcnow().isoformat() + "Z",
    "generator": "Boardwalk Playground Studio",
}


FASTAPI_SERVER_PY = '''"""
Minimal FastAPI service scaffold generated by Boardwalk Playground Studio.

Notes:
- This file is intentionally small. Install dependencies:
    pip install fastapi "uvicorn[standard]"
- Run locally:
    uvicorn server:app --reload --port 8000
"""

from fastapi import FastAPI
from fastapi.responses import JSONResponse
import os

app = FastAPI(title="{project_name} Backend", version="0.1.0")

@app.get("/health")
def health():
    return JSONResponse({{"status": "ok", "service": "{project_name}"}})

@app.get("/")
def root():
    return JSONResponse({{"message": "Welcome to {project_name} backend"}})

@app.get("/api/hello")
def api_hello():
    return JSONResponse({{"success": True, "message": "hello from {project_name}"}})

# Example: add more routes here or import routers from a 'routes' package.
'''

DOCKERFILE = '''# Dockerfile - minimal FastAPI container
FROM python:3.11-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir fastapi "uvicorn[standard]"
EXPOSE 8000
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
'''

PROCFILE = "web: uvicorn server:app --host 0.0.0.0 --port $PORT\n"

README_SNIPPET = """# Backend service

This folder contains a minimal FastAPI scaffold and a service descriptor.

Quick start (local):
1. Create a virtualenv and activate it.
2. pip install fastapi "uvicorn[standard]"
3. uvicorn server:app --reload --port 8000

Docker:
1. docker build -t {project_name_lower}-backend .
2. docker run -p 8000:8000 {project_name_lower}-backend
"""

SERVICE_HELPER = '''"""
service_helper.py

Small helper to load the backend-services.json descriptor and expose metadata.
"""

import json
from pathlib import Path
from typing import Dict, Any

ROOT = Path(__file__).parent
DESC_PATH = ROOT / "backend-services.json"

def load_descriptor() -> Dict[str, Any]:
    if not DESC_PATH.exists():
        return {{}}
    try:
        return json.loads(DESC_PATH.read_text(encoding="utf-8"))
    except Exception:
        return {{}}
'''

class BackendServiceModule(GenModule):
    """
    Generates backend service descriptor and minimal scaffold files.
    """

    def run(self, ctx: GenContext) -> None:
        root: Path = ctx.project_path
        FileOps.ensure_dir(root, ctx)

        try:
            # Descriptor
            descriptor = DEFAULT_DESCRIPTOR.copy()
            descriptor["services"][0]["name"] = getattr(ctx, "project_name", descriptor["services"][0]["name"])
            descriptor["generated_at"] = datetime.utcnow().isoformat() + "Z"
            FileOps.write_file(root / "backend-services.json", json.dumps(descriptor, indent=2), ctx)

            # server.py (FastAPI scaffold)
            server_code = FASTAPI_SERVER_PY.format(project_name=getattr(ctx, "project_name", "app"))
            FileOps.write_file(root / "server.py", server_code, ctx)

            # Dockerfile and Procfile
            FileOps.write_file(root / "Dockerfile", DOCKERFILE, ctx)
            FileOps.write_file(root / "Procfile", PROCFILE, ctx)

            # README snippet
            readme = README_SNIPPET.format(project_name=getattr(ctx, "project_name", "app"), project_name_lower=getattr(ctx, "project_name", "app").lower().replace(" ", "-"))
            FileOps.write_file(root / "BACKEND_README.md", readme, ctx)

            # service helper
            FileOps.write_file(root / "service_helper.py", SERVICE_HELPER, ctx)

            # update metadata if present
            try:
                meta_path = root / "metadata.json"
                meta = {}
                if meta_path.exists():
                    meta = json.loads(meta_path.read_text(encoding="utf-8"))
                meta.setdefault("services", [])
                if "default" not in meta["services"]:
                    meta["services"].append("default")
                FileOps.write_file(meta_path, json.dumps(meta, indent=2), ctx)
            except Exception:
                pass

            ctx.log("Backend service scaffold created", {"path": str(root / "backend-services.json")})
        except Exception as e:
            try:
                ctx.error(f"BackendServiceModule failed: {e}")
            except Exception:
                ctx.log(f"BackendServiceModule failed: {e}")
            raise
