# backend/generator/modules/project_scaffold.py
from pathlib import Path
import json
from datetime import datetime
from ..base import GenContext, FileOps, GenModule


class ProjectScaffoldModule(GenModule):
    """
    Upgraded project scaffold module.

    Improvements:
    - Creates a conventional web project layout (root files + src + public + assets)
    - Writes metadata.json and README.md
    - Adds .gitignore and basic package.json (optional)
    - Uses FileOps helpers and logs actions to GenContext
    - Safe writes and idempotent directory creation
    """

    def run(self, ctx: GenContext) -> None:
        try:
            root: Path = ctx.project_path
            FileOps.ensure_dir(root, ctx)

            # --- root index.html (points to /public or /src depending on app_type) ---
            index_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>{ctx.project_name}</title>
  <link rel="stylesheet" href="style.css" />
</head>
<body>
  <div id="app">
    <h1>{ctx.project_name}</h1>
    <p>Generated by Boardwalk Playground Studio on {datetime.utcnow().isoformat()}Z</p>
    <div id="root"></div>
  </div>
  <script src="app.js"></script>
</body>
</html>
"""
            FileOps.write_file(root / "index.html", index_html, ctx)

            # --- app.js (entry) ---
            app_js = (
                "// Entry script for the generated app\n"
                "document.addEventListener('DOMContentLoaded', () => {\n"
                "  const root = document.getElementById('root');\n"
                "  if (root) root.innerHTML = `<p>Welcome to {name}</p>`;\n"
                "  console.log('Boardwalk app initialized');\n"
                "});\n".replace("{name}", ctx.project_name)
            )
            FileOps.write_file(root / "app.js", app_js, ctx)

            # --- style.css ---
            style_css = (
                "/* Basic styles generated by Boardwalk Playground */\n"
                ":root { --bg: #0b1220; --fg: #e6eef8; --accent: #2563eb; }\n"
                "body { margin:0; font-family: Inter, system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial; background:var(--bg); color:var(--fg); }\n"
                "#app { padding:24px; }\n"
                "a { color:var(--accent); }\n"
            )
            FileOps.write_file(root / "style.css", style_css, ctx)

            # --- config.json (stores generator prompt + metadata) ---
            config = {
                "name": ctx.project_name,
                "type": getattr(ctx, "app_type", "generic"),
                "generated_at": datetime.utcnow().isoformat() + "Z",
                "prompt": getattr(ctx, "prompt", "")[:4096],
            }
            FileOps.write_file(root / "config.json", json.dumps(config, indent=2), ctx)

            # --- metadata.json and README ---
            metadata = {
                "project": ctx.project_name,
                "created_at": datetime.utcnow().isoformat() + "Z",
                "generator": "Boardwalk Playground",
                "app_type": config["type"],
            }
            FileOps.write_file(root / "metadata.json", json.dumps(metadata, indent=2), ctx)

            readme = f"# {ctx.project_name}\n\nGenerated by Boardwalk Playground Studio.\n\n**App type:** {config['type']}\n\nGenerated at {metadata['created_at']}\n"
            FileOps.write_file(root / "README.md", readme, ctx)

            # --- .gitignore ---
            gitignore = """# Node / build artifacts
node_modules/
dist/
.build/
.env
*.log
"""
            FileOps.write_file(root / ".gitignore", gitignore, ctx)

            # --- optional package.json for web projects ---
            if config["type"] in ("web", "generic", "worker"):
                pkg = {
                    "name": ctx.project_name.lower().replace(" ", "-"),
                    "version": "0.1.0",
                    "private": True,
                    "scripts": {"start": "serve .", "build": "echo 'no build step'"},
                }
                FileOps.write_file(root / "package.json", json.dumps(pkg, indent=2), ctx)

            # --- create src and public folders for better structure ---
            src_dir = root / "src"
            public_dir = root / "public"
            assets_dir = public_dir / "assets"
            FileOps.ensure_dir(src_dir, ctx)
            FileOps.ensure_dir(public_dir, ctx)
            FileOps.ensure_dir(assets_dir, ctx)

            # --- scaffold a simple src/main.js if app_type is web/microcontroller hint ---
            src_main = (
                "// src/main.js\n"
                "export function mount(el) {\n"
                "  el.innerHTML = `<div><strong>{name}</strong> — app mounted</div>`;\n"
                "}\n".replace("{name}", ctx.project_name)
            )
            FileOps.write_file(src_dir / "main.js", src_main, ctx)

            # --- public/index.html (for SPA setups) ---
            public_index = f"""<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{ctx.project_name} (public)</title>
    <link rel="stylesheet" href="/style.css" />
  </head>
  <body>
    <div id="app">This is the public folder for {ctx.project_name}</div>
    <script type="module">
      import {{ mount }} from '/src/main.js';
      mount(document.getElementById('app'));
    </script>
  </body>
</html>
"""
            FileOps.write_file(public_dir / "index.html", public_index, ctx)

            # --- small asset example ---
            FileOps.write_file(assets_dir / "placeholder.txt", "assets folder", ctx)

            ctx.log("Project scaffold created", {"project": ctx.project_name, "path": str(root)})

        except Exception as e:
            # Use ctx.log or ctx.error depending on GenContext API
            try:
                ctx.error(f"ProjectScaffoldModule failed: {e}")
            except Exception:
                ctx.log(f"ProjectScaffoldModule failed: {e}")
            raise
