# backend/generator/modules/worker_cloudflare.py
"""
Upgraded WorkerCloudflareModule

Improvements:
- Writes a production-ready Cloudflare Worker scaffold (worker.js) with example routes and env binding hints
- Generates a `wrangler.toml` with sensible defaults and comments
- Adds a `package.json` and `tsconfig.json` for optional TypeScript development
- Adds a small `deploy_helper.py` that can validate wrangler config and optionally run `wrangler publish` (requires wrangler installed)
- Writes a README with usage notes and security guidance
- Updates project metadata to record that a Worker scaffold was added
- Uses FileOps and GenContext for safe writes and logging
"""

from pathlib import Path
import json
from datetime import datetime
from typing import Dict, Any

from ..base import GenContext, FileOps, GenModule


WORKER_JS = '''/**
 * worker.js
 *
 * Minimal Cloudflare Worker scaffold generated by Boardwalk Playground Studio.
 *
 * Notes:
 * - This file is ESM-style and uses the `fetch` handler signature.
 * - Replace or extend the routes below with your app logic.
 * - For durable bindings, KV, R2, or secrets, reference `env` in the handler.
 */

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    // simple routing
    if (url.pathname === "/health") {
      return new Response(JSON.stringify({ status: "ok", service: env.SERVICE_NAME || "worker" }), {
        status: 200,
        headers: { "Content-Type": "application/json" },
      });
    }

    if (url.pathname === "/api/echo" && request.method === "POST") {
      try {
        const body = await request.json();
        return new Response(JSON.stringify({ success: true, echo: body }), {
          status: 200,
          headers: { "Content-Type": "application/json" },
        });
      } catch (err) {
        return new Response(JSON.stringify({ success: false, error: "invalid json" }), { status: 400, headers: { "Content-Type": "application/json" } });
      }
    }

    // default response
    return new Response("Worker for generated app is alive.", { status: 200 });
  }
};
'''

WRANGLER_TOML = '''# wrangler.toml - generated by Boardwalk Playground Studio
name = "{name}"
main = "worker.js"
compatibility_date = "{compat_date}"
# Uncomment and set account_id and zone_id for production deployments
# account_id = ""
# zone_id = ""
# Example environment variables and bindings:
# [vars]
# SERVICE_NAME = "{name}"
#
# [[kv_namespaces]]
# binding = "APP_KV"
# id = "your-kv-id"
#
# [[r2_buckets]]
# binding = "MEDIA_R2"
# bucket_name = "media"
'''

PACKAGE_JSON = '''{
  "name": "{pkg_name}",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "build": "echo \\"No build step configured\\"",
    "deploy": "wrangler publish"
  },
  "devDependencies": {}
}
'''

TSCONFIG_JSON = '''{
  "compilerOptions": {
    "target": "ES2020",
    "module": "ESNext",
    "moduleResolution": "Node",
    "lib": ["ES2020", "WebWorker"],
    "strict": true,
    "esModuleInterop": true,
    "skipLibCheck": true
  },
  "include": ["./**/*"]
}
'''

DEPLOY_HELPER = '''"""
deploy_helper.py

Optional helper to validate wrangler.toml and run `wrangler publish`.
Requires `wrangler` CLI installed and available on PATH.

Usage:
  python deploy_helper.py --validate
  python deploy_helper.py --publish

This script is conservative: it will not modify files and will only run commands if explicitly requested.
"""

import subprocess
import json
import sys
from pathlib import Path

def _run(cmd, cwd=None):
    print("> " + " ".join(cmd))
    subprocess.run(cmd, cwd=cwd, check=True)

def validate_wrangler():
    # wrangler has a `wrangler whoami` and `wrangler publish --dry-run` options in some versions.
    try:
        _run(["wrangler", "--version"])
        print("wrangler appears to be installed.")
    except Exception as e:
        print("wrangler not found on PATH:", e)
        return False
    return True

def publish():
    if not validate_wrangler():
        raise RuntimeError("wrangler not available")
    _run(["wrangler", "publish"])

if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Deploy helper for Cloudflare Worker scaffold")
    parser.add_argument("--validate", action="store_true", help="Check wrangler availability")
    parser.add_argument("--publish", action="store_true", help="Run wrangler publish")
    args = parser.parse_args()
    if args.validate:
        validate_wrangler()
    if args.publish:
        publish()
'''

README = """# Cloudflare Worker scaffold

This folder contains a minimal Cloudflare Worker scaffold generated by Boardwalk Playground Studio.

Files:
- `worker.js` — the Worker entrypoint (ESM).
- `wrangler.toml` — Wrangler configuration (edit account_id/zone_id for production).
- `package.json` — optional helper scripts (deploy).
- `deploy_helper.py` — optional script to validate and run `wrangler publish`.

Quick start:
1. Install Wrangler: `npm install -g wrangler` (or follow Cloudflare docs).
2. Edit `wrangler.toml` to set `account_id` and any bindings (KV, R2).
3. Run locally: `wrangler dev` or `wrangler publish` to deploy.

Security and notes:
- Do not commit secrets into `wrangler.toml`. Use environment variables or Cloudflare secrets.
- For durable objects, KV, or R2 bindings, follow Cloudflare docs and add the appropriate sections to `wrangler.toml`.
"""

class WorkerCloudflareModule(GenModule):
    """
    Creates a basic Cloudflare Worker scaffold and helper files.
    """

    def run(self, ctx: GenContext) -> None:
        root: Path = ctx.project_path
        FileOps.ensure_dir(root, ctx)

        try:
            project_name = getattr(ctx, "project_name", "worker-app")
            safe_name = project_name.lower().replace(" ", "-")
            # worker.js
            FileOps.write_file(root / "worker.js", WORKER_JS, ctx)

            # wrangler.toml
            wrangler = WRANGLER_TOML.format(
                name=safe_name,
                compat_date=(datetime.utcnow().strftime("%Y-%m-%d")),
                compat_date_full=(datetime.utcnow().isoformat()),
                compat_date_short=(datetime.utcnow().strftime("%Y-%m-%d")),
                name_full=project_name,
                name_safe=safe_name,
                compat_date_comment="",
            )
            # Use a simpler format substitution to avoid unused keys
            wrangler = WRANGLER_TOML.format(name=safe_name, compat_date=datetime.utcnow().strftime("%Y-%m-%d"))
            FileOps.write_file(root / "wrangler.toml", wrangler, ctx)

            # package.json and tsconfig.json
            FileOps.write_file(root / "package.json", PACKAGE_JSON.format(pkg_name=safe_name), ctx)
            FileOps.write_file(root / "tsconfig.json", TSCONFIG_JSON, ctx)

            # deploy helper
            FileOps.write_file(root / "deploy_helper.py", DEPLOY_HELPER, ctx)

            # README
            FileOps.write_file(root / "WORKER_README.md", README, ctx)

            # update metadata
            try:
                meta_path = root / "metadata.json"
                meta = {}
                if meta_path.exists():
                    meta = json.loads(meta_path.read_text(encoding="utf-8"))
                meta.setdefault("features", [])
                if "cloudflare_worker" not in meta["features"]:
                    meta["features"].append("cloudflare_worker")
                meta["cloudflare_worker_added_at"] = datetime.utcnow().isoformat() + "Z"
                FileOps.write_file(meta_path, json.dumps(meta, indent=2), ctx)
            except Exception:
                pass

            ctx.log("Cloudflare Worker scaffold created", {"path": str(root / "worker.js")})
        except Exception as e:
            try:
                ctx.error(f"WorkerCloudflareModule failed: {e}")
            except Exception:
                ctx.log(f"WorkerCloudflareModule failed: {e}")
            raise
